import { ObjectPathConfig } from '../../src/types'

export const deepRedactPaths: string[][] = [
  ['firstName'],
  ['lastName'],
  ['surname'],
  ['maidenName'],
  ['email'],
  ['phone'],
  ['username'],
  ['password'],
  ['birthDate'],
  ['ip'],
  ['macAddress'],
  ['wallet'],
  ['address'],
  ['addressLine1'],
  ['addressLine2'],
  ['street'],
  ['city'],
  ['postalCode'],
  ['coordinates'],
  ['iban'],
  ['cardNumber'],
  ['ein'],
  ['ssn'],
]

export const deepRedactComplexPaths: Array<ObjectPathConfig | Array<string | number | RegExp>> = [
  ['phone'],
  ['password'],
  ['birthDate'],
  ['ip'],
  ['ein'],
  ['ssn'],
  [/iban|(payment)?cardNumber|wallet/i],
  { path: ['address'], retainStructure: true, fuzzyKeyMatch: true, caseSensitiveKeyMatch: false },
  { path: ['name'], fuzzyKeyMatch: true, caseSensitiveKeyMatch: false },
]

export const fastRedactBlacklistedKeys = [
  '*.firstName',
  '*.lastName',
  '*.maidenName',
  '*.email',
  '*.phone',
  '*.password',
  '*.birthDate',
  '*.ip',
  '*.macAddress',
  '*.address.street',
  '*.address.city',
  '*.address.state',
  '*.address.postalCode',
  '*.address.country',
  '*.address.coordinates.lat',
  '*.address.coordinates.lng',
  '*.bank.cardNumber',
  '*.bank.iban',
  '*.wallet',
  '*.company.address.street',
  '*.company.address.city',
  '*.company.address.state',
  '*.company.address.postalCode',
  '*.company.address.country',
  '*.company.address.coordinates.lat',
  '*.company.address.coordinates.lng',
  '*.ein',
  '*.ssn',
]

export const ObGlobPatterns = [
  '**/!(*user*)*[nN]ame*',
  '**/email',
  '**/phone',
  '**/password',
  '**/birthDate',
  '**/ip',
  '**/macAddress',
  '**/address/**',
  '**/cardNumber',
  '**/iban',
  '**/wallet',
  '**/ein',
  '**/ssn',
]

export const stringPattern = /"(email|phone|password|birthDate|ip|macAddress|address.*?city|state|postalCode|country|iban|cardNumber|wallet|ein|ssn|firstName|lastName|maidenName|username)":"[^"]*"/gi

export const xmlPattern = /<(email|phone|password|birthDate|ip|macAddress|address.*?city|state|postalCode|country|iban|cardNumber|wallet|ein|ssn|firstName|lastName|maidenName|username)>([^<]+)<\/\1>/gi
