import { renderTable, type TableData } from './_renderTable'

const tableData: TableData = [
  {
    key: 'blacklistedKeys',
    description: 'Deeply compare names of these keys against the keys in your object.',
    type: 'array',
    options: 'Array<string￨BlacklistKeyConfig>',
    default: '[]',
    required: 'N',
  },
  {
    key: 'stringTests',
    description: 'Array of regular expressions to perform against string values, whether that value is a flat string or nested within an object.',
    type: 'array',
    options: 'RegExp[]',
    default: '[]',
    required: 'N',
  },
  {
    key: 'fuzzyKeyMatch',
    description: 'Loosely compare key names by checking if the key name of your unredacted object is included anywhere within the name of your blacklisted key. For example, is "pass" (your key) included in "password" (from config).',
    type: 'boolean',
    options: '',
    default: 'false',
    required: 'N',
  },
  {
    key: 'caseSensitiveKeyMatch',
    description: 'Loosely compare key names by normalising the strings. This involves removing non-word characters and transforms the string to lowercase. This means you never have to worry having to list duplicate keys in different formats such as snake_case, camelCase, PascalCase or any other case.',
    type: 'boolean',
    options: '',
    default: 'true',
    required: 'N',
  },
  {
    key: 'remove',
    description: 'Determines whether or not to remove the key from the object when it is redacted.',
    type: 'boolean',
    options: '',
    default: 'false',
    required: 'N',
  },
  {
    key: 'retainStructure',
    description: 'Determines whether or not keep all nested values of a key that is going to be redacted. Circular references are always removed.',
    type: 'boolean',
    options: '',
    default: 'false',
    required: 'N',
  },
  {
    key: 'replacement',
    description: 'When a value is going to be redacted, what would you like to replace it with?',
    type: 'string',
    options: '',
    default: '[REDACTED]',
    required: 'N',
  },
  {
    key: 'replaceStringByLength',
    description: 'When a string value is going to be replaced, optionally replace it by repeating the `replacement` to match the length of the value. For example, if `replaceStringByLength` were set to `true` and `replacement` was set to "x", then redacting "secret" would return "xxxxxx". This is sometimes useful for debugging purposes, although it may be less secure as it could give hints to the original value.',
    type: 'boolean',
    options: '',
    default: 'false',
    required: 'N',
  },
  {
    key: 'types',
    description: 'JS types (values of `typeof` keyword). Only values with a typeof equal to `string`, `number`, `bigint`, `boolean` or `object` may be redacted. The other types are only listed as options to keep TypeScript happy, so you never need to list them.',
    type: 'array',
    options: 'Array<\'string\'￨\'number\'￨\'bigint\'￨\'boolean\'￨\'symbol\'￨\'undefined\'￨\'object\'￨\'function\'>',
    default: '[\'string\']',
    required: 'N',
  },
  {
    key: 'serialise',
    description: 'Determines whether or not to serialise the object after redacting. Typical use cases for this are when you want to send it over the network or save to a file, both of which are common use cases for redacting sensitive information.',
    type: 'boolean',
    options: '',
    default: 'true',
    required: 'N',
  },
  {
    key: 'unsupportedTransformer',
    description: 'When an unsafe value is encountered or a value that cannot be serialised. By default, this function will transform an unsupported value `Unsupported` object. BigInt values are converted a string. Dates are returned using their own `toISOString` method. Regular expressions are returned as objects with their `source` and `flags` values. Errors are converted objects. This is useful when you have a custom class that you would like to redact. For safety reasons, you should always transform a BigInt to avoid JSON.stringify throwing an error.',
    type: '(value: unknown) => unknown',
    options: '',
    default: 'DeepRedact.transformUnsupported',
    required: 'N',
  },
]

export const mainOptions = renderTable(tableData)
